import type { DiningType, FoodCategory, FoodImageSource, FoodStatus, ReviewStatus, SaleStatus, ShopType } from "@/types/domain";

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      areas: {
        Row: {
          id: string;
          name: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["areas"]["Insert"]>;
        Relationships: [];
      };
      admin_users: {
        Row: {
          id: string;
          email: string;
          role: "owner" | "editor" | "viewer";
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role: "owner" | "editor" | "viewer";
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["admin_users"]["Insert"]>;
        Relationships: [];
      };
      admin_auth_pkce_attempts: {
        Row: {
          id: string;
          code_verifier: string;
          next_path: string;
          created_at: string;
          expires_at: string;
          used_at: string | null;
        };
        Insert: {
          id: string;
          code_verifier: string;
          next_path?: string;
          created_at?: string;
          expires_at: string;
          used_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["admin_auth_pkce_attempts"]["Insert"]>;
        Relationships: [];
      };
      shops: {
        Row: {
          id: string;
          area_id: string | null;
          name: string;
          type: ShopType;
          official_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          area_id?: string | null;
          name: string;
          type?: ShopType;
          official_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["shops"]["Insert"]>;
        Relationships: [];
      };
      foods: {
        Row: {
          id: string;
          shop_id: string | null;
          area_id: string | null;
          name: string;
          normalized_name: string;
          category: FoodCategory;
          price: number | null;
          price_min: number | null;
          price_max: number | null;
          price_note: string | null;
          price_source_url: string | null;
          price_last_checked_at: string | null;
          price_confidence_score: number | null;
          dining_type: DiningType | null;
          dining_type_confidence_score: number | null;
          dining_type_reason: string | null;
          description: string | null;
          official_url: string | null;
          source_url: string;
          image_url: string | null;
          sale_status: SaleStatus | null;
          sale_start_date: string | null;
          sale_end_date: string | null;
          sale_period_label: string | null;
          is_completable: boolean | null;
          start_date: string | null;
          end_date: string | null;
          status: FoodStatus;
          is_limited: boolean;
          confidence_score: number;
          name_quality_score: number;
          display_quality: "high" | "medium" | "low";
          extraction_source_count: number;
          review_status: ReviewStatus;
          hidden: boolean;
          duplicate_group_id: string | null;
          manual_override: boolean;
          composite_menu: boolean;
          canonical_food: boolean;
          canonical_group_id: string | null;
          flavor: string | null;
          event_name: string | null;
          collaboration_name: string | null;
          release_period: string | null;
          seasonal_version: string | null;
          rarity: "standard" | "limited" | "event" | "rare" | null;
          zukan_number: number | null;
          trusted_placeholder: boolean;
          last_checked_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id?: string | null;
          area_id?: string | null;
          name: string;
          normalized_name: string;
          category?: FoodCategory;
          price?: number | null;
          price_min?: number | null;
          price_max?: number | null;
          price_note?: string | null;
          price_source_url?: string | null;
          price_last_checked_at?: string | null;
          price_confidence_score?: number | null;
          dining_type?: DiningType | null;
          dining_type_confidence_score?: number | null;
          dining_type_reason?: string | null;
          description?: string | null;
          official_url?: string | null;
          source_url: string;
          image_url?: string | null;
          sale_status?: SaleStatus | null;
          sale_start_date?: string | null;
          sale_end_date?: string | null;
          sale_period_label?: string | null;
          is_completable?: boolean | null;
          start_date?: string | null;
          end_date?: string | null;
          status?: FoodStatus;
          is_limited?: boolean;
          confidence_score?: number;
          name_quality_score?: number;
          display_quality?: "high" | "medium" | "low";
          extraction_source_count?: number;
          review_status?: ReviewStatus;
          hidden?: boolean;
          duplicate_group_id?: string | null;
          manual_override?: boolean;
          composite_menu?: boolean;
          canonical_food?: boolean;
          canonical_group_id?: string | null;
          flavor?: string | null;
          event_name?: string | null;
          collaboration_name?: string | null;
          release_period?: string | null;
          seasonal_version?: string | null;
          rarity?: "standard" | "limited" | "event" | "rare" | null;
          zukan_number?: number | null;
          trusted_placeholder?: boolean;
          last_checked_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["foods"]["Insert"]>;
        Relationships: [];
      };
      manual_foods: {
        Row: {
          id: string;
          name: string;
          normalized_name: string;
          name_en: string | null;
          category: FoodCategory;
          category_tags: string[];
          price: number | null;
          area_name: string;
          shop_name: string;
          sale_status: "active" | "paused" | "ended" | "unknown";
          public_state: "published" | "draft";
          hidden: boolean;
          start_date: string | null;
          end_date: string | null;
          image_url: string | null;
          source_url: string;
          admin_notes: string | null;
          created_by: string;
          updated_by: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          name: string;
          normalized_name: string;
          name_en?: string | null;
          category?: FoodCategory;
          category_tags?: string[];
          price?: number | null;
          area_name: string;
          shop_name: string;
          sale_status?: "active" | "paused" | "ended" | "unknown";
          public_state?: "published" | "draft";
          hidden?: boolean;
          start_date?: string | null;
          end_date?: string | null;
          image_url?: string | null;
          source_url: string;
          admin_notes?: string | null;
          created_by: string;
          updated_by: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["manual_foods"]["Insert"]>;
        Relationships: [];
      };
      food_overrides: {
        Row: {
          food_id: string;
          name: string | null;
          name_en: string | null;
          price: number | null;
          price_min: number | null;
          price_max: number | null;
          price_note: string | null;
          area_name: string | null;
          area_id: string | null;
          shop_name: string | null;
          shop_id: string | null;
          category: FoodCategory | null;
          category_tags: string[] | null;
          image_path: string | null;
          image_source_url: string | null;
          info_source_url: string | null;
          sale_status: "active" | "paused" | "ended" | "unknown" | null;
          status: FoodStatus | null;
          hidden: boolean | null;
          admin_source_type: string | null;
          admin_confidence: string | null;
          admin_notes: string | null;
          is_deleted: boolean;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          food_id: string;
          name?: string | null;
          name_en?: string | null;
          price?: number | null;
          price_min?: number | null;
          price_max?: number | null;
          price_note?: string | null;
          area_name?: string | null;
          area_id?: string | null;
          shop_name?: string | null;
          shop_id?: string | null;
          category?: FoodCategory | null;
          category_tags?: string[] | null;
          image_path?: string | null;
          image_source_url?: string | null;
          info_source_url?: string | null;
          sale_status?: "active" | "paused" | "ended" | "unknown" | null;
          status?: FoodStatus | null;
          hidden?: boolean | null;
          admin_source_type?: string | null;
          admin_confidence?: string | null;
          admin_notes?: string | null;
          is_deleted?: boolean;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["food_overrides"]["Insert"]>;
        Relationships: [];
      };
      food_override_revisions: {
        Row: {
          id: string;
          food_id: string;
          version: number;
          snapshot: Json;
          action: string;
          actor_email: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          food_id: string;
          version: number;
          snapshot: Json;
          action: string;
          actor_email?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["food_override_revisions"]["Insert"]>;
        Relationships: [];
      };
      food_images: {
        Row: {
          id: string;
          food_id: string;
          image_url: string;
          source_type: FoodImageSource;
          source_url: string | null;
          priority: number;
          alt_text: string | null;
          alt: string | null;
          width: number | null;
          height: number | null;
          image_confidence_score: number;
          image_match_score: number;
          category_image_match_score: number;
          image_source_context: string | null;
          image_match_reason: string | null;
          image_mismatch_reason: string | null;
          image_verified: boolean;
          is_shared_too_much: boolean;
          has_watermark: boolean;
          watermark_reason: string | null;
          image_candidate_score: number | null;
          image_source_name: string | null;
          official_confirmed: boolean;
          image_last_checked_at: string | null;
          enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          food_id: string;
          image_url: string;
          source_type: FoodImageSource;
          source_url?: string | null;
          priority?: number;
          alt_text?: string | null;
          alt?: string | null;
          width?: number | null;
          height?: number | null;
          image_confidence_score?: number;
          image_match_score?: number;
          category_image_match_score?: number;
          image_source_context?: string | null;
          image_match_reason?: string | null;
          image_mismatch_reason?: string | null;
          image_verified?: boolean;
          is_shared_too_much?: boolean;
          has_watermark?: boolean;
          watermark_reason?: string | null;
          image_candidate_score?: number | null;
          image_source_name?: string | null;
          official_confirmed?: boolean;
          image_last_checked_at?: string | null;
          enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["food_images"]["Insert"]>;
        Relationships: [];
      };
      image_candidates: {
        Row: {
          id: string;
          food_id: string;
          candidate_url: string;
          thumbnail_url: string | null;
          source_page: string | null;
          source_domain: string | null;
          source_name: string | null;
          image_width: number | null;
          image_height: number | null;
          image_match_score: number;
          has_watermark: boolean;
          watermark_reason: string | null;
          is_product_photo: boolean;
          is_storefront: boolean;
          is_menu_board: boolean;
          is_collage: boolean;
          is_character_only: boolean;
          is_closeup_food: boolean;
          product_match_score: number;
          is_approved: boolean;
          is_rejected: boolean;
          official_confirmed: boolean;
          reasons: Json;
          query: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          food_id: string;
          candidate_url: string;
          thumbnail_url?: string | null;
          source_page?: string | null;
          source_domain?: string | null;
          source_name?: string | null;
          image_width?: number | null;
          image_height?: number | null;
          image_match_score?: number;
          has_watermark?: boolean;
          watermark_reason?: string | null;
          is_product_photo?: boolean;
          is_storefront?: boolean;
          is_menu_board?: boolean;
          is_collage?: boolean;
          is_character_only?: boolean;
          is_closeup_food?: boolean;
          product_match_score?: number;
          is_approved?: boolean;
          is_rejected?: boolean;
          official_confirmed?: boolean;
          reasons?: Json;
          query?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["image_candidates"]["Insert"]>;
        Relationships: [];
      };
      crawl_logs: {
        Row: {
          id: string;
          source_name: string;
          source_url: string;
          status: "success" | "failed";
          message: string | null;
          added_count: number;
          updated_count: number;
          inactive_count: number;
          pages_crawled: number;
          foods_found: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          source_name: string;
          source_url: string;
          status: "success" | "failed";
          message?: string | null;
          added_count?: number;
          updated_count?: number;
          inactive_count?: number;
          pages_crawled?: number;
          foods_found?: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["crawl_logs"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
