import type { Area, DiningType, DisplayQuality, FoodCategory, FoodImageSource, FoodLocation, FoodStatus, ImageCandidate, PriceSource, ReviewStatus, SaleStatus, Shop, ShopType } from "../../types/domain";

export type GeneratedImage = {
  id: string;
  foodId: string;
  imageUrl: string;
  sourceType: FoodImageSource;
  sourceUrl?: string;
  altText?: string;
  alt?: string;
  width?: number;
  height?: number;
  imageConfidenceScore?: number;
  imageMatchScore?: number;
  categoryImageMatchScore?: number;
  imageSourceContext?: string;
  imageMatchReason?: string;
  imageMismatchReason?: string;
  imageVerified?: boolean;
  isSharedTooMuch?: boolean;
  hasWatermark?: boolean;
  watermarkReason?: string;
  imageCandidateScore?: number;
  imageSourceName?: string;
  officialConfirmed?: boolean;
  imageApproved?: boolean;
  image_approved?: boolean;
  manuallyAdded?: boolean;
  manually_added?: boolean;
  imageLastCheckedAt?: string;
  image_last_checked_at?: string;
  priority: number;
  enabled: boolean;
};

export type GeneratedFood = {
  id: string;
  shopId: string;
  areaId: string;
  name: string;
  normalizedName: string;
  normalized_name: string;
  category: FoodCategory;
  price?: number;
  priceMin?: number;
  price_min?: number;
  priceMax?: number;
  price_max?: number;
  priceNote?: string;
  price_note?: string;
  priceSource?: PriceSource;
  price_source?: PriceSource;
  priceSourceUrl?: string;
  price_source_url?: string;
  priceLastCheckedAt?: string;
  price_last_checked_at?: string;
  priceConfidenceScore?: number;
  price_confidence_score?: number;
  diningType?: DiningType;
  dining_type?: DiningType;
  diningTypeConfidenceScore?: number;
  dining_type_confidence_score?: number;
  diningTypeReason?: string;
  dining_type_reason?: string;
  description?: string;
  officialUrl?: string;
  official_url?: string;
  sourceUrl: string;
  source_url: string;
  startDate?: string;
  start_date?: string;
  endDate?: string;
  end_date?: string;
  status: FoodStatus;
  isLimited: boolean;
  is_limited: boolean;
  confidenceScore: number;
  confidence_score: number;
  nameQualityScore: number;
  name_quality_score: number;
  displayQuality: DisplayQuality;
  display_quality: DisplayQuality;
  extractionSourceCount: number;
  extraction_source_count: number;
  reviewStatus: ReviewStatus;
  review_status: ReviewStatus;
  hidden: boolean;
  duplicateGroupId?: string;
  duplicate_group_id?: string;
  manualOverride: boolean;
  manual_override: boolean;
  compositeMenu: boolean;
  composite_menu: boolean;
  canonicalFood: boolean;
  canonical_food: boolean;
  canonicalGroupId?: string;
  canonical_group_id?: string;
  flavor?: string;
  eventName?: string;
  event_name?: string;
  collaborationName?: string;
  collaboration_name?: string;
  releasePeriod?: string;
  release_period?: string;
  seasonalVersion?: string;
  seasonal_version?: string;
  rarity?: "standard" | "limited" | "event" | "rare";
  zukanNumber?: number;
  zukan_number?: number;
  trustedPlaceholder: boolean;
  trusted_placeholder: boolean;
  lastCheckedAt: string;
  last_checked_at: string;
  imageUrl?: string;
  image_url?: string;
  saleStatus?: SaleStatus;
  sale_status?: SaleStatus;
  saleStartDate?: string | null;
  sale_start_date?: string | null;
  saleEndDate?: string | null;
  sale_end_date?: string | null;
  salePeriodLabel?: string;
  sale_period_label?: string;
  isCompletable?: boolean;
  is_completable?: boolean;
  sourceNames: string[];
  source_names: string[];
  rejectionReasons: string[];
  rejection_reasons: string[];
  locations: FoodLocation[];
  representativeImageUrl?: string;
  representative_image_url?: string;
  area: Area;
  shop: Shop;
  images: GeneratedImage[];
};

export type GeneratedShop = Shop & {
  type: ShopType;
  foodCount: number;
};

export type GeneratedArea = Area & {
  foodCount: number;
};

export type GeneratedDataset = {
  generatedAt: string;
  summary: {
    totalCandidates: number;
    generatedFoods: number;
    approved: number;
    pending: number;
    rejected: number;
    hidden: number;
    duplicateHidden: number;
    withImages: number;
    highQuality: number;
    officialImages: number;
    verifiedOfficialImages: number;
    placeholderImages: number;
    imageMismatchExcluded: number;
    nameFiltered: number;
    compositeCandidates: number;
    sharedImages: number;
  };
  foods: GeneratedFood[];
};

export type GeneratedImageCandidate = ImageCandidate;
