create table if not exists public.image_candidates (
  id uuid primary key default gen_random_uuid(),
  food_id uuid not null references public.foods(id) on delete cascade,
  candidate_url text not null,
  thumbnail_url text,
  source_page text,
  source_domain text,
  source_name text,
  image_width integer,
  image_height integer,
  image_match_score integer not null default 0,
  has_watermark boolean not null default false,
  watermark_reason text,
  is_product_photo boolean not null default false,
  is_storefront boolean not null default false,
  is_menu_board boolean not null default false,
  is_collage boolean not null default false,
  is_character_only boolean not null default false,
  is_closeup_food boolean not null default false,
  product_match_score integer not null default 0,
  is_approved boolean not null default false,
  is_rejected boolean not null default false,
  official_confirmed boolean not null default false,
  reasons jsonb not null default '[]'::jsonb,
  query text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(food_id, candidate_url)
);
